// web-components/src/submit-button.js
export default (() => {
	const SELECTOR = 'jpe-submit-button';

	if (!!customElements.get(SELECTOR)) {
		return;
	}

	class el extends HTMLElement {
		constructor() {
			super()
			this.attachShadow({ mode: 'open' })
			this.shadowRoot.innerHTML = `<style>:host{display:block;}</style>`
			
			this.output = document.createElement('button');
			this.output.setAttribute('type', 'submit');
			this.output.addEventListener('click', () => {
				const form = this.closest('form');

				if (!form.reportValidity()) {
					return;
				}

				this.output.setAttribute('disabled', 'true');
	
				const data = new FormData(form);
				const typeMap = {
					string: 'stringValue',
					number: 'doubleValue'
				};
				const fields = {
					createdOn: {
						integerValue: Date.now().toString()
					}
				};
	
				data.forEach((value, key) => {
					fields[key] = {
						[typeMap[typeof value]]: value
					};
				});
	
				fetch(
					`https://firestore.googleapis.com/v1/projects/jaspero-jms/databases/(default)/documents/inquiries`,
					{
						method: 'POST',
						body: JSON.stringify({fields})
					}
				)
					.finally(() => 
						this.output.removeAttribute('disabled')
					);
			});
			
			this.shadowRoot.appendChild(this.output);
		}

		static get observedAttributes() {
			return ['label'];
		}

		connectedCallback() {
			this.output.innerText = this.getAttribute('label');
		}

		attributeChangedCallback() {
			this.connectedCallback();
		}
	}

	customElements.define(SELECTOR, el);
})()

// client/projects/submit-button/src/app/submit-button.component.ts
import {Component, ElementRef, Input} from '@angular/core';
import {of, from} from 'rxjs';

@Component({
  selector: 'jpe-submit-button',
  template: `<button type="submit" [jpLoadClick]="submit()">{{label}}</button>`,
  styles: [``]
})
export class SubmitButtonComponent {
  constructor(
    private el: ElementRef
  ) {}

  @Input() label = 'Submit';
  
  submit() {
    return () => {

      const form = this.el.nativeElement.closest('form');

      if (!form.reportValidity()) {
        return of(true);
      }

      const data = new FormData(form);
      const typeMap = {
        string: 'stringValue',
        number: 'doubleValue'
      };
      const fields = {
        createdOn: {
          integerValue: Date.now().toString()
        }
      };

      data.forEach((value, key) => {
        fields[key] = {
          [typeMap[typeof value]]: value
        };
      });

      return from(fetch(
        `https://firestore.googleapis.com/v1/projects/jaspero-jms/databases/(default)/documents/inquiries`,
        {
          method: 'POST',
          body: JSON.stringify({fields})
        }
      ));
    };
  }
}
